version: '3.8'
services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: aiai
      MARIADB_USER: aiai
      MARIADB_PASSWORD: aiai1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev", "--http-port=8081"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  mariadb_data:
